# theme: just-the-docs
# remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: PageHelper Docs

description: A small utility which enhance the webpage functionality.
theme: just-the-docs

url: https://lets-script.com

permalink: pretty

aux_links:
  Lets-script: https://lets-script.com

# baseurl: /pagehelper-docs

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

back_to_top: true
back_to_top_text: "Back to top"

footer_content: '<a href="https://discord.gg/ZXumFzxkcg">Discord</a>, <span>QQ group:418474680</span>'
#   <a href="https://lets-script.com">Lets-script</a> &copy; 2021
#last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
#last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
# <ph ph-css-to-head="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css" inline/>
# <code ph-highlight="/highlight" ph-params="lang::javascript" id="demo-code">
# <ph ph-css-to-head="/highlight/" ph-params="css::highlight.js" inline />