# theme: just-the-docs
# remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: PageHelper Docs

description: A small utility which enhance the webpage functionality.
theme: just-the-docs

url: https://lets-script.com

permalink: pretty

aux_links:
  Lets-script: https://lets-script.com

# baseurl: /pagehelper-docs

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# footer_content:
#   <a href="https://lets-script.com">Lets-script</a> &copy; 2021