# theme: just-the-docs
# remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: PageHelper Docs

description: A small utility which enhance the webpage functionality.
theme: just-the-docs

url: https://lets-script.com

permalink: pretty

aux_links:
  Template Repository: https://jianglibo.github.com/pagehelper-docs/